// <auto-generated />
using System;
using BusinessObjects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessObjects.Migrations
{
    [DbContext(typeof(SportMatchmakingContext))]
    [Migration("20260310034208_Initia3")]
    partial class Initia3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessObjects.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<byte?>("SkillLevel")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex(new[] { "RoleId" }, "IX_AppUsers_RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ_AppUsers_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "UserName" }, "UQ_AppUsers_UserName")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("BusinessObjects.ChatMessage", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MessageId"));

                    b.Property<DateTime?>("EditedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<long>("ThreadId")
                        .HasColumnType("bigint");

                    b.HasKey("MessageId");

                    b.HasIndex("SenderUserId");

                    b.HasIndex(new[] { "ThreadId", "SentAt" }, "IX_ChatMessages_Thread_Time");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("BusinessObjects.ChatThread", b =>
                {
                    b.Property<long>("ThreadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ThreadId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<long?>("PostId")
                        .HasColumnType("bigint");

                    b.Property<byte>("ThreadType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.HasKey("ThreadId");

                    b.HasIndex("PostId");

                    b.ToTable("ChatThreads");
                });

            modelBuilder.Entity("BusinessObjects.ChatThreadMember", b =>
                {
                    b.Property<long>("ThreadId")
                        .HasColumnType("bigint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("ThreadId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatThreadMembers");
                });

            modelBuilder.Entity("BusinessObjects.EmailVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ExpireTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("OTP")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("Id");

                    b.ToTable("EmailVerification", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.JoinRequest", b =>
                {
                    b.Property<long>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RequestId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("DecidedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("DecidedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("GuestNames")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PartySize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<long>("PostId")
                        .HasColumnType("bigint");

                    b.Property<int>("RequesterUserId")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.HasKey("RequestId");

                    b.HasIndex("DecidedByUserId");

                    b.HasIndex("RequesterUserId");

                    b.HasIndex(new[] { "PostId", "Status", "CreatedAt" }, "IX_JoinRequests_Post_Status");

                    b.HasIndex(new[] { "PostId", "RequesterUserId" }, "UX_JoinRequests_Unique")
                        .IsUnique();

                    b.ToTable("JoinRequests");
                });

            modelBuilder.Entity("BusinessObjects.MatchPost", b =>
                {
                    b.Property<long>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PostId"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("EndTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<decimal?>("FeePerPerson")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("GoogleMapsUrl")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("bit");

                    b.Property<string>("LocationText")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<byte>("MatchType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)4);

                    b.Property<byte?>("SkillMax")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("SkillMin")
                        .HasColumnType("tinyint");

                    b.Property<int>("SlotsNeeded")
                        .HasColumnType("int");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.HasKey("PostId");

                    b.HasIndex(new[] { "CreatorUserId" }, "IX_Posts_Creator");

                    b.HasIndex(new[] { "City", "District" }, "IX_Posts_Location");

                    b.HasIndex(new[] { "SportId", "Status", "StartTime" }, "IX_Posts_Search");

                    b.ToTable("MatchPosts");
                });

            modelBuilder.Entity("BusinessObjects.Notification", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NotificationId"));

                    b.Property<string>("Body")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("DataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReadAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex(new[] { "UserId", "IsRead", "CreatedAt" }, "IX_Notifications_User_Read");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BusinessObjects.PostParticipant", b =>
                {
                    b.Property<long>("PostId")
                        .HasColumnType("bigint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("LeftAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("PartySize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<byte>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)2);

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.HasKey("PostId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PostParticipants");
                });

            modelBuilder.Entity("BusinessObjects.Report", b =>
                {
                    b.Property<long>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReportId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("ReasonCode")
                        .HasColumnType("tinyint");

                    b.Property<int>("ReporterUserId")
                        .HasColumnType("int");

                    b.Property<string>("Resolution")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<long?>("TargetPostId")
                        .HasColumnType("bigint");

                    b.Property<byte>("TargetType")
                        .HasColumnType("tinyint");

                    b.Property<int?>("TargetUserId")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.HasIndex("ReporterUserId");

                    b.HasIndex("TargetPostId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("BusinessObjects.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex(new[] { "Name" }, "UQ_Roles_Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("BusinessObjects.Sport", b =>
                {
                    b.Property<int>("SportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SportId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TeamMax")
                        .HasColumnType("int");

                    b.Property<int?>("TeamMin")
                        .HasColumnType("int");

                    b.HasKey("SportId");

                    b.HasIndex(new[] { "ImageId" }, "IX_Sports_ImageId");

                    b.HasIndex(new[] { "Name" }, "UQ_Sports_Name")
                        .IsUnique();

                    b.ToTable("Sports");
                });

            modelBuilder.Entity("BusinessObjects.SportImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ImageId");

                    b.ToTable("SportImages");
                });

            modelBuilder.Entity("BusinessObjects.AppUser", b =>
                {
                    b.HasOne("BusinessObjects.Role", "Role")
                        .WithMany("AppUsers")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_AppUsers_Roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BusinessObjects.ChatMessage", b =>
                {
                    b.HasOne("BusinessObjects.AppUser", "SenderUser")
                        .WithMany("ChatMessages")
                        .HasForeignKey("SenderUserId")
                        .IsRequired()
                        .HasConstraintName("FK_ChatMessages_Sender");

                    b.HasOne("BusinessObjects.ChatThread", "Thread")
                        .WithMany("ChatMessages")
                        .HasForeignKey("ThreadId")
                        .IsRequired()
                        .HasConstraintName("FK_ChatMessages_Thread");

                    b.Navigation("SenderUser");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("BusinessObjects.ChatThread", b =>
                {
                    b.HasOne("BusinessObjects.MatchPost", "Post")
                        .WithMany("ChatThreads")
                        .HasForeignKey("PostId")
                        .HasConstraintName("FK_ChatThreads_Post");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("BusinessObjects.ChatThreadMember", b =>
                {
                    b.HasOne("BusinessObjects.ChatThread", "Thread")
                        .WithMany("ChatThreadMembers")
                        .HasForeignKey("ThreadId")
                        .IsRequired()
                        .HasConstraintName("FK_ChatMembers_Thread");

                    b.HasOne("BusinessObjects.AppUser", "User")
                        .WithMany("ChatThreadMembers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_ChatMembers_User");

                    b.Navigation("Thread");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObjects.JoinRequest", b =>
                {
                    b.HasOne("BusinessObjects.AppUser", "DecidedByUser")
                        .WithMany("JoinRequestDecidedByUsers")
                        .HasForeignKey("DecidedByUserId")
                        .HasConstraintName("FK_JoinRequests_Decider");

                    b.HasOne("BusinessObjects.MatchPost", "Post")
                        .WithMany("JoinRequests")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK_JoinRequests_Post");

                    b.HasOne("BusinessObjects.AppUser", "RequesterUser")
                        .WithMany("JoinRequestRequesterUsers")
                        .HasForeignKey("RequesterUserId")
                        .IsRequired()
                        .HasConstraintName("FK_JoinRequests_Requester");

                    b.Navigation("DecidedByUser");

                    b.Navigation("Post");

                    b.Navigation("RequesterUser");
                });

            modelBuilder.Entity("BusinessObjects.MatchPost", b =>
                {
                    b.HasOne("BusinessObjects.AppUser", "CreatorUser")
                        .WithMany("MatchPosts")
                        .HasForeignKey("CreatorUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Posts_Users");

                    b.HasOne("BusinessObjects.Sport", "Sport")
                        .WithMany("MatchPosts")
                        .HasForeignKey("SportId")
                        .IsRequired()
                        .HasConstraintName("FK_Posts_Sports");

                    b.Navigation("CreatorUser");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("BusinessObjects.Notification", b =>
                {
                    b.HasOne("BusinessObjects.AppUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObjects.PostParticipant", b =>
                {
                    b.HasOne("BusinessObjects.MatchPost", "Post")
                        .WithMany("PostParticipants")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK_Part_Post");

                    b.HasOne("BusinessObjects.AppUser", "User")
                        .WithMany("PostParticipants")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Part_User");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObjects.Report", b =>
                {
                    b.HasOne("BusinessObjects.AppUser", "ReporterUser")
                        .WithMany("ReportReporterUsers")
                        .HasForeignKey("ReporterUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Reports_Reporter");

                    b.HasOne("BusinessObjects.MatchPost", "TargetPost")
                        .WithMany("Reports")
                        .HasForeignKey("TargetPostId")
                        .HasConstraintName("FK_Reports_TargetPost");

                    b.HasOne("BusinessObjects.AppUser", "TargetUser")
                        .WithMany("ReportTargetUsers")
                        .HasForeignKey("TargetUserId")
                        .HasConstraintName("FK_Reports_TargetUser");

                    b.Navigation("ReporterUser");

                    b.Navigation("TargetPost");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("BusinessObjects.Sport", b =>
                {
                    b.HasOne("BusinessObjects.SportImage", "Image")
                        .WithMany("Sports")
                        .HasForeignKey("ImageId")
                        .HasConstraintName("FK_Sports_SportImages");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("BusinessObjects.AppUser", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("ChatThreadMembers");

                    b.Navigation("JoinRequestDecidedByUsers");

                    b.Navigation("JoinRequestRequesterUsers");

                    b.Navigation("MatchPosts");

                    b.Navigation("Notifications");

                    b.Navigation("PostParticipants");

                    b.Navigation("ReportReporterUsers");

                    b.Navigation("ReportTargetUsers");
                });

            modelBuilder.Entity("BusinessObjects.ChatThread", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("ChatThreadMembers");
                });

            modelBuilder.Entity("BusinessObjects.MatchPost", b =>
                {
                    b.Navigation("ChatThreads");

                    b.Navigation("JoinRequests");

                    b.Navigation("PostParticipants");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("BusinessObjects.Role", b =>
                {
                    b.Navigation("AppUsers");
                });

            modelBuilder.Entity("BusinessObjects.Sport", b =>
                {
                    b.Navigation("MatchPosts");
                });

            modelBuilder.Entity("BusinessObjects.SportImage", b =>
                {
                    b.Navigation("Sports");
                });
#pragma warning restore 612, 618
        }
    }
}
